export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const AUTH_LOADING = "AUTH_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_LOADING = "CLEAR_LOADING";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const GET_USER = "GET_USER";
export const USER_LOADING = "USER_LOADING";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const PROJECT_LOADING = "PROJECT_LOADING";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PROJECTPROFILES = "GET_PROJECTPROFILES";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const TICKET_LOADING = "TICKET_LOADING";
export const GET_TICKET = "GET_TICKET";
export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
